name: Kurlyk
options:
  minimumXcodeGenVersion: 2.25.0
  bundleIdPrefix: com.test-apps
  createIntermediateGroups: true
  carthageExecutablePath: mint run Carthage/Carthage
  findCarthageFrameworks: true
  deploymentTarget:
    iOS: "15.0" # my default minimum iOS version

fileGroups:
  - project.yml
  - AllTests.xctestplan
      
settings:
  base:
    DEVELOPMENT_TEAM: "YA3F4FB73R"
    
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.28.1
  AuthenticationFeature:
    path: AuthenticationFeature
  DesignSystem:
    path: DesignSystem
  ComponentsKit:
    path: ComponentsKit
  Domain:
    path: Domain

targets:

  # Main app target. Here is a place to merge all features with infrastructure.
  Kurlyk:
    type: application
    platform: iOS
    sources: [Kurlyk/Sources]
    info:
      path: Kurlyk/Sources/Application/Info.plist
      properties:
        CFBundleDisplayName: "Kurlyk"
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1 # iPhone only, not iPad
        BUNDLE_SHORT_VERSION: "1.0.0" # App version
        BUNDLE_VERSION: "0"
        
    dependencies:
      - package: AuthenticationFeature
      
    scheme:
      testTargets:
        - KurlykTests
      gatherCoverageData: true
  
  # Tests for main app.
  KurlykTests:
    platform: iOS
    type: bundle.unit-test
    sources: [Kurlyk/Tests]
    dependencies:
      - target: Kurlyk
